export type IndustryType = 'hvac' | 'plumbing' | 'electrical' | 'mechanical' | 'elevator' | 'home_automation' | 'general';

export type TerminologyKey = 
  | 'job' | 'jobs'
  | 'client' | 'clients' 
  | 'equipment' | 'equipmentSingular'
  | 'technician' | 'technicians'
  | 'serviceRequest' | 'serviceRequests'
  | 'schedule' | 'dispatch'
  | 'workOrder' | 'callOut'
  | 'myJobs' | 'myCalendar';

export type IndustryTerminology = Record<TerminologyKey, string>;

export const INDUSTRY_TERMINOLOGY: Record<IndustryType, IndustryTerminology> = {
  hvac: {
    job: 'Service Call',
    jobs: 'Service Calls',
    client: 'Customer',
    clients: 'Customers',
    equipment: 'Units',
    equipmentSingular: 'Unit',
    technician: 'HVAC Technician',
    technicians: 'HVAC Technicians',
    serviceRequest: 'Service Request',
    serviceRequests: 'Service Requests',
    schedule: 'Dispatch Board',
    dispatch: 'Dispatch',
    workOrder: 'Service Call',
    callOut: 'Call Out',
    myJobs: 'My Calls',
    myCalendar: 'My Schedule',
  },
  plumbing: {
    job: 'Service Call',
    jobs: 'Service Calls',
    client: 'Customer',
    clients: 'Customers',
    equipment: 'Fixtures',
    equipmentSingular: 'Fixture',
    technician: 'Plumber',
    technicians: 'Plumbers',
    serviceRequest: 'Service Request',
    serviceRequests: 'Service Requests',
    schedule: 'Schedule',
    dispatch: 'Dispatch',
    workOrder: 'Work Order',
    callOut: 'Emergency Call',
    myJobs: 'My Calls',
    myCalendar: 'My Schedule',
  },
  electrical: {
    job: 'Work Order',
    jobs: 'Work Orders',
    client: 'Client',
    clients: 'Clients',
    equipment: 'Equipment',
    equipmentSingular: 'Equipment',
    technician: 'Electrician',
    technicians: 'Electricians',
    serviceRequest: 'Work Request',
    serviceRequests: 'Work Requests',
    schedule: 'Schedule',
    dispatch: 'Assign',
    workOrder: 'Work Order',
    callOut: 'Service Call',
    myJobs: 'My Orders',
    myCalendar: 'My Schedule',
  },
  mechanical: {
    job: 'Work Order',
    jobs: 'Work Orders',
    client: 'Account',
    clients: 'Accounts',
    equipment: 'Assets',
    equipmentSingular: 'Asset',
    technician: 'Mechanic',
    technicians: 'Mechanics',
    serviceRequest: 'Maintenance Request',
    serviceRequests: 'Maintenance Requests',
    schedule: 'Schedule',
    dispatch: 'Assign',
    workOrder: 'Work Order',
    callOut: 'Breakdown Call',
    myJobs: 'My Orders',
    myCalendar: 'My Schedule',
  },
  elevator: {
    job: 'Service Call',
    jobs: 'Service Calls',
    client: 'Building Manager',
    clients: 'Building Managers',
    equipment: 'Units',
    equipmentSingular: 'Unit',
    technician: 'Elevator Mechanic',
    technicians: 'Elevator Mechanics',
    serviceRequest: 'Service Call',
    serviceRequests: 'Service Calls',
    schedule: 'Dispatch Board',
    dispatch: 'Dispatch',
    workOrder: 'Work Order',
    callOut: 'Emergency Call',
    myJobs: 'My Calls',
    myCalendar: 'My Schedule',
  },
  home_automation: {
    job: 'Project',
    jobs: 'Projects',
    client: 'Homeowner',
    clients: 'Homeowners',
    equipment: 'Devices',
    equipmentSingular: 'Device',
    technician: 'Installer',
    technicians: 'Installers',
    serviceRequest: 'Support Request',
    serviceRequests: 'Support Requests',
    schedule: 'Schedule',
    dispatch: 'Assign',
    workOrder: 'Work Order',
    callOut: 'Service Call',
    myJobs: 'My Projects',
    myCalendar: 'My Schedule',
  },
  general: {
    job: 'Job',
    jobs: 'Jobs',
    client: 'Client',
    clients: 'Clients',
    equipment: 'Equipment',
    equipmentSingular: 'Equipment',
    technician: 'Technician',
    technicians: 'Technicians',
    serviceRequest: 'Service Request',
    serviceRequests: 'Service Requests',
    schedule: 'Schedule',
    dispatch: 'Dispatch',
    workOrder: 'Work Order',
    callOut: 'Call Out',
    myJobs: 'My Jobs',
    myCalendar: 'My Calendar',
  },
};

export function getIndustryTerminology(industry?: IndustryType | null): IndustryTerminology {
  return INDUSTRY_TERMINOLOGY[industry || 'general'] || INDUSTRY_TERMINOLOGY.general;
}
