/**
 * Generate realistic, deterministic embeddings for the E2E AI seed corpus.
 *
 * Why this exists
 * ───────────────
 * The field-assistant edge function embeds each user query at request time
 * with OpenAI `text-embedding-3-small`, then abstains (returns a structured
 * "insufficient_retrieval_coverage" JSON instead of a streamed answer) when
 * fewer than MIN_RELEVANT_CHUNKS relevant chunks are retrieved. The E2E seed
 * chunks must therefore carry embeddings from the SAME model, or grounded
 * queries score marginally and the pipeline abstains — which is exactly what
 * turned the chromium-ai-pipeline suite red.
 *
 * This script embeds every chunk text in TEST_DOCUMENTS once and writes a
 * checked-in fixture (e2e/fixtures/chunk-embeddings.json) keyed by a SHA-256
 * of the chunk text. Test-time seeding reads that fixture, so CI stays fully
 * offline and deterministic — no live OpenAI calls happen during tests.
 *
 * Run (one-off, only when chunk texts change)
 * ───────────────────────────────────────────
 *   OPENAI_API_KEY=sk-… npx tsx scripts/generate-e2e-embeddings.ts
 *
 * The key is read from the environment (or a gitignored .env / .env.test) and
 * is NEVER written to the fixture. Use a non-production key.
 */
import { createHash } from 'crypto';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { config } from 'dotenv';
import { TEST_DOCUMENTS } from '../e2e/helpers/ai-test-data';

// Pick up a key from a gitignored .env / .env.test if present (never committed).
config({ path: '.env' });
config({ path: '.env.test' });

const MODEL = 'text-embedding-3-small';
const DIMENSION = 1536;
const OUT_PATH = join('e2e', 'fixtures', 'chunk-embeddings.json');

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error(
    '✗ OPENAI_API_KEY is not set.\n' +
      '  Provide a non-production OpenAI key (env var, or a gitignored .env) and re-run:\n' +
      '    OPENAI_API_KEY=sk-… npx tsx scripts/generate-e2e-embeddings.ts',
  );
  process.exit(1);
}

/** Stable fixture key for a chunk text — must match e2e/helpers/ai-seed-helpers.ts. */
function keyForText(text: string): string {
  return createHash('sha256').update(text.trim()).digest('hex');
}

async function embed(text: string): Promise<number[]> {
  const res = await fetch('https://api.openai.com/v1/embeddings', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({ model: MODEL, input: text }),
  });
  if (!res.ok) {
    throw new Error(`OpenAI embeddings request failed (${res.status}): ${await res.text()}`);
  }
  const json = (await res.json()) as { data?: Array<{ embedding?: number[] }> };
  const vec = json.data?.[0]?.embedding;
  if (!Array.isArray(vec) || vec.length !== DIMENSION) {
    throw new Error(`Unexpected embedding shape: length=${vec?.length ?? 'none'}`);
  }
  // Round to 8 decimals → smaller, stable-diff fixture (cosine impact < 1e-7).
  return vec.map((v) => Math.round(v * 1e8) / 1e8);
}

async function main(): Promise<void> {
  // Collect unique chunk texts (dedupe identical texts across documents).
  const texts: string[] = [];
  const seen = new Set<string>();
  for (const doc of TEST_DOCUMENTS) {
    for (const chunk of doc.chunks) {
      const key = keyForText(chunk.text);
      if (!seen.has(key)) {
        seen.add(key);
        texts.push(chunk.text);
      }
    }
  }

  console.log(`Embedding ${texts.length} unique chunk texts with ${MODEL}…`);
  const embeddings: Record<string, number[]> = {};
  for (const text of texts) {
    const key = keyForText(text);
    embeddings[key] = await embed(text);
    console.log(`  ✓ ${key.slice(0, 12)}  ${text.slice(0, 56)}…`);
  }

  // Sort keys lexically so the committed fixture has stable diffs.
  const sorted: Record<string, number[]> = {};
  for (const key of Object.keys(embeddings).sort()) sorted[key] = embeddings[key];

  const fixture = {
    _comment:
      'AUTO-GENERATED by scripts/generate-e2e-embeddings.ts — do not edit by hand. ' +
      'Keys are sha256(chunk_text.trim()); values are text-embedding-3-small vectors. ' +
      'Regenerate after changing any chunk text in e2e/helpers/ai-test-data.ts.',
    model: MODEL,
    dimension: DIMENSION,
    count: Object.keys(sorted).length,
    embeddings: sorted,
  };

  writeFileSync(OUT_PATH, JSON.stringify(fixture, null, 2) + '\n');
  console.log(`\nWrote ${OUT_PATH} (${fixture.count} embeddings, model ${MODEL}).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
